theme: league
transition: slide
revealjs_config:
  parallaxBackgroundImage: 'https://www.netdevices.fr/wp-content/themes/vossen/img/backgrounds/bg-shortcodes.jpg'
  parallaxBackgroundSize: 1920px 1080px
  history: true
  slideNumber: true

# If you want to print pdf change parallaxBackgroundSize to 1056px 770px
